import { icons } from "@/utils/icons";

export const tiptapToolbarIcons = {
  bold: icons.bold,
  italic: icons.italic,
  strikethrough: icons.strikethrough,
  code: icons.inlineCode,
  link: icons.link,
  subscript: icons.subscript,
  superscript: icons.superscript,
  image: icons.image,
  h1: icons.heading1,
  h2: icons.heading2,
  h3: icons.heading3,
  h4: icons.heading4,
  h5: icons.heading5,
  h6: icons.heading6,
  paragraph: icons.paragraph,
  chevronDown: icons.chevronDown,
  indent: icons.indent,
  outdent: icons.outdent,
  bulletList: icons.unorderedList,
  orderedList: icons.orderedList,
  blockquote: icons.blockquote,
  divider: icons.divider,
  table: icons.table,
  removeList: icons.removeList,
  nestQuote: icons.nestQuote,
  unnestQuote: icons.unnestQuote,
  removeQuote: icons.removeQuote,
  addRowAbove: icons.rowAbove,
  addRowBelow: icons.rowBelow,
  addColLeft: icons.colLeft,
  addColRight: icons.colRight,
  deleteRow: icons.deleteRow,
  deleteCol: icons.deleteCol,
  deleteTable: icons.deleteTable,
  alignLeft: icons.alignLeft,
  alignCenter: icons.alignCenter,
  alignRight: icons.alignRight,
  alignAllLeft: icons.alignAllLeft,
  alignAllCenter: icons.alignAllCenter,
  alignAllRight: icons.alignAllRight,
  formatTable: icons.formatTable,
} as const;

export const TIPTAP_FORMAT_BUTTONS = [
  { icon: tiptapToolbarIcons.bold, title: "Bold", markType: "bold" },
  { icon: tiptapToolbarIcons.italic, title: "Italic", markType: "italic" },
  { icon: tiptapToolbarIcons.strikethrough, title: "Strikethrough", markType: "strike" },
  { icon: tiptapToolbarIcons.subscript, title: "Subscript", markType: "subscript" },
  { icon: tiptapToolbarIcons.superscript, title: "Superscript", markType: "superscript" },
  { icon: tiptapToolbarIcons.link, title: "Link", markType: "link" },
  { icon: tiptapToolbarIcons.code, title: "Inline Code", markType: "code" },
] as const;

export const TIPTAP_HEADING_BUTTONS = [
  { icon: tiptapToolbarIcons.h1, title: "Heading 1", level: 1 },
  { icon: tiptapToolbarIcons.h2, title: "Heading 2", level: 2 },
  { icon: tiptapToolbarIcons.h3, title: "Heading 3", level: 3 },
  { icon: tiptapToolbarIcons.h4, title: "Heading 4", level: 4 },
  { icon: tiptapToolbarIcons.h5, title: "Heading 5", level: 5 },
  { icon: tiptapToolbarIcons.h6, title: "Heading 6", level: 6 },
  { icon: tiptapToolbarIcons.paragraph, title: "Paragraph", level: 0 },
] as const;
