// @vitest-environment node
/**
 * One coverage threshold source, not two.
 *
 * `vitest.config.ts` carries ratchet-only floors and is what `pnpm test:coverage`
 * and `pnpm check:all` actually enforce. `.claude/tdd-guardian/config.json` was
 * generated by `tdd-guardian:init` with a placeholder `100/100/100/100` that
 * nothing enforced — so the repository carried two disagreeing answers to
 * "what is the coverage bar?", and a plan could be written against the wrong one.
 *
 * This gate makes the guardian config declare vitest as authoritative rather
 * than compete with it. It fails if someone reintroduces numeric thresholds
 * there, or if the two ever drift apart again.
 *
 * WI-0.2 — align the coverage-threshold sources
 *
 * @coordinates-with vitest.config.ts — the authoritative floors
 * @coordinates-with .claude/tdd-guardian/config.json — must not compete
 * @module test/coverageThresholdSources.test
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(__dirname, "../..");

function guardianConfig(): Record<string, unknown> {
  return JSON.parse(readFileSync(resolve(ROOT, ".claude/tdd-guardian/config.json"), "utf8"));
}

/** The four floors as declared in vitest.config.ts, read from source. */
function vitestFloors(): Record<string, number> {
  const src = readFileSync(resolve(ROOT, "vitest.config.ts"), "utf8");
  const block = src.slice(src.indexOf("thresholds: {"));
  const floors: Record<string, number> = {};
  for (const key of ["statements", "branches", "functions", "lines"]) {
    const match = new RegExp(`\\b${key}:\\s*([0-9.]+)`).exec(block);
    if (match) floors[key] = Number(match[1]);
  }
  return floors;
}

describe("coverage thresholds have exactly one source", () => {
  it("vitest.config.ts declares all four floors", () => {
    // Guards the parser above: if the config is restructured so these stop
    // being found, this fails loudly instead of the drift check passing on an
    // empty object.
    const floors = vitestFloors();
    expect(Object.keys(floors).sort()).toEqual([
      "branches",
      "functions",
      "lines",
      "statements",
    ]);
    for (const value of Object.values(floors)) expect(value).toBeGreaterThan(0);
  });

  it("the guardian config does not declare competing numeric thresholds", () => {
    const config = guardianConfig();
    const thresholds = config.thresholds as Record<string, unknown> | undefined;
    if (thresholds === undefined) return; // removed entirely — also acceptable

    const numeric = Object.entries(thresholds).filter(([, v]) => typeof v === "number");
    expect(
      numeric.length === 0
        ? ""
        : `\n  .claude/tdd-guardian/config.json still declares numeric thresholds ` +
          `${JSON.stringify(Object.fromEntries(numeric))}.\n` +
          `  vitest.config.ts is the enforced source. Set them to null, or delete\n` +
          `  the block, so there is one answer to "what is the coverage bar?".\n`,
    ).toBe("");
  });

  it("the guardian config names vitest as authoritative", () => {
    const raw = readFileSync(resolve(ROOT, ".claude/tdd-guardian/config.json"), "utf8");
    expect(raw).toContain("vitest.config.ts");
  });
});
