// @vitest-environment node
// WI-UI1.5 — the static --syntax-* fallback in index.css IS the catalog.
/**
 * The runtime palette comes from ThemeTokens.syntax via applyTheme; index.css
 * only carries a static fallback for first paint / print / SSR. This pins the
 * fallback to the paper (light) and night (dark) catalog values, replacing
 * the deleted styles/syntax-palette.css — the "generated by a test" contract
 * D11 asked for: edit the catalog and this fails until the statics follow.
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { themes } from "./themes";

const css = readFileSync("src/styles/index.css", "utf8");

function block(selector: string): string {
  const start = css.indexOf(`${selector} {`);
  expect(start, `${selector} block`).toBeGreaterThan(-1);
  return css.slice(start, css.indexOf("}", start));
}

function declared(blockText: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const m of blockText.matchAll(/--syntax-([a-z]+)\s*:\s*([^;]+);/g)) {
    out[m[1]] = m[2].trim();
  }
  return out;
}

describe("index.css syntax fallback tracks the catalog", () => {
  it(":root carries paper's syntax palette", () => {
    expect(declared(block(":root"))).toEqual(themes.paper.syntax);
  });

  it(".dark-theme carries night's syntax palette", () => {
    expect(declared(block(".dark-theme"))).toEqual(themes.night.syntax);
  });
});
