/**
 * Tests for the Tauri npm/crate version gate (scripts/check-tauri-versions.mjs).
 *
 * The gate exists because `tauri build` (release) rejects a Tauri package whose
 * npm and Rust crate versions drift onto different major/minor releases, and
 * nothing before release catches it. These tests pin the parsing + comparison
 * logic, including the exact v0.9.0 regression (tauri-plugin-log 2.9.0 crate vs
 * @tauri-apps/plugin-log 2.8.0 npm).
 */
import { describe, it, expect } from "vitest";
// @ts-expect-error — plain .mjs module without type declarations
import {
  parseCargoLock,
  crateForNpm,
  sameMajorMinor,
  findMismatches,
} from "./check-tauri-versions.mjs";

describe("parseCargoLock", () => {
  it("extracts name -> version for each [[package]] block", () => {
    const lock = `# This file is automatically generated by Cargo.
version = 4

[[package]]
name = "tauri"
version = "2.11.5"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tauri-plugin-log"
version = "2.9.0"
dependencies = [
 "log",
]
`;
    const crates = parseCargoLock(lock);
    expect(crates["tauri"]).toBe("2.11.5");
    expect(crates["tauri-plugin-log"]).toBe("2.9.0");
  });

  it("does not mistake a top-level `version = 4` for a package version", () => {
    // The lockfile format line has no preceding `name =`, so it must be ignored.
    const crates = parseCargoLock('version = 4\n\n[[package]]\nname = "x"\nversion = "1.2.3"\n');
    expect(crates["x"]).toBe("1.2.3");
    expect(Object.keys(crates)).toEqual(["x"]);
  });
});

describe("crateForNpm", () => {
  it("maps api -> tauri and plugin-X -> tauri-plugin-X", () => {
    expect(crateForNpm("api")).toBe("tauri");
    expect(crateForNpm("plugin-log")).toBe("tauri-plugin-log");
    expect(crateForNpm("plugin-fs")).toBe("tauri-plugin-fs");
  });

  it("returns null for packages with no runtime crate counterpart (cli)", () => {
    expect(crateForNpm("cli")).toBeNull();
  });
});

describe("sameMajorMinor", () => {
  it("compares on major.minor, ignoring patch", () => {
    expect(sameMajorMinor("2.9.0", "2.9.5")).toBe(true);
    expect(sameMajorMinor("2.9.0", "2.8.0")).toBe(false); // the v0.9.0 release break
    expect(sameMajorMinor("2.9.0", "3.9.0")).toBe(false);
  });
});

describe("findMismatches", () => {
  it("flags a plugin whose npm and crate drift on minor (the v0.9.0 regression)", () => {
    const npm = { "plugin-log": "2.8.0", api: "2.11.1" };
    const crates = { "tauri-plugin-log": "2.9.0", tauri: "2.11.5" };
    const out = findMismatches(npm, crates);
    expect(out).toHaveLength(1);
    expect(out[0]).toMatchObject({
      crate: "tauri-plugin-log",
      crateVer: "2.9.0",
      npm: "@tauri-apps/plugin-log",
      npmVer: "2.8.0",
    });
  });

  it("passes when every shared pair aligns on major/minor (patch may differ)", () => {
    const npm = { "plugin-log": "2.9.0", api: "2.11.1" };
    const crates = { "tauri-plugin-log": "2.9.3", tauri: "2.11.5" };
    expect(findMismatches(npm, crates)).toEqual([]);
  });

  it("skips packages with no crate counterpart (rust-only plugin, or cli)", () => {
    // cli -> null; plugin-shell has no resolved tauri-plugin-shell (rust-only usage).
    const npm = { cli: "2.11.4", "plugin-shell": "2.3.0" };
    const crates = { tauri: "2.11.5" };
    expect(findMismatches(npm, crates)).toEqual([]);
  });
});
