//! Command registry for the Tauri invoke handler.
//!
//! Extracted from lib.rs, which is the app composition root and was at its file-size
//! baseline. A registry grows by exactly one line per command — that is not logic bloat,
//! but the size gate cannot tell the difference, and a frozen baseline must never be
//! raised to make room for growth it will keep having. Moving the list out means adding
//! a command costs a line HERE, where lines are cheap, instead of in the composition
//! root, where they are not.
//!
//! `generate_handler!` must expand at the `.invoke_handler(...)` call site, so this is a
//! macro rather than a function.

/// Every `#[tauri::command]` the app exposes to the frontend.
#[macro_export]
macro_rules! all_commands {
    () => {
        tauri::generate_handler![
            window_status::report_window_status,
            window_status::set_window_attention,
            window_status::clear_window_attention,
            window_status::get_window_statuses,
            window_status::focus_window,
            file_open::get_pending_file_opens,
            asset_access::grant_asset_access,
            external_editor::open_in_external_editor,
            menu::update_recent_files,
            menu::update_recent_workspaces,
            menu::refresh_genies_menu,
            menu::hide_genies_menu,
            menu::rebuild_menu,
            menu::update_menu_accelerators,
            menu::sync_view_menu_state,
            menu::set_browser_menu_enabled,
            menu::set_locale,
            window_manager::open_file_in_new_window,
            window_manager::open_workspace_in_new_window,
            window_manager::open_workspace_with_files_in_new_window,
            window_manager::open_settings_window,
            window_manager::close_window,
            window_manager::force_quit,
            window_manager::request_quit,
            quit::cancel_quit,
            quit::set_confirm_quit,
            watcher::start_watching,
            watcher::stop_watching,
            file_tree::list_directory_entries,
            file_ops::get_file_size_bytes,
            workspace::read_workspace_config,
            workspace::write_workspace_config,
            quarantine::strip_workspace_quarantine_cmd,
            mcp_server::mcp_bridge_start,
            mcp_server::mcp_bridge_stop,
            mcp_server::mcp_server_status,
            mcp_server::mcp_sidecar_health,
            mcp_server::mcp_bridge_client_count,
            mcp_server::mcp_bridge_connected_clients,
            mcp_bridge::commands::mcp_bridge_respond,
            mcp_bridge::commands::mcp_bridge_heartbeat,
            mcp_bridge_path_guard::mcp_bridge_check_path,
            mcp_config::commands::mcp_config_diagnose,
            mcp_config::commands::mcp_config_preview,
            mcp_config::commands::mcp_config_install,
            mcp_config::commands::mcp_config_uninstall,
            hot_exit::commands::hot_exit_capture,
            hot_exit::commands::hot_exit_restore,
            hot_exit::commands::hot_exit_inspect_session,
            hot_exit::commands::hot_exit_clear_session,
            hot_exit::commands::hot_exit_restore_multi_window,
            hot_exit::commands::hot_exit_get_window_state,
            hot_exit::commands::hot_exit_window_restore_complete,
            tab_transfer::detach_tab_to_new_window,
            tab_transfer::transfer_tab_to_existing_window,
            tab_transfer::claim_tab_transfer,
            tab_transfer::find_drop_target_window,
            tab_transfer::focus_existing_window,
            tab_transfer::remove_tab_from_window,
            workspace_transfer::detach_workspace_to_new_window,
            workspace_transfer::claim_workspace_transfer,
            workspace_transfer::ack_workspace_transfer,
            workspace_transfer::cancel_workspace_transfer,
            shell_env::get_default_shell,
            shell_env::get_login_shell_path,
            shell_env::list_available_shells,
            genies::commands::get_genies_dir,
            genies::commands::list_genies,
            genies::commands::read_genie,
            workflow::commands::run_workflow,
            workflow::commands::cancel_workflow,
            workflow::commands::respond_workflow_approval,
            gha_workflow::commands::gha_lint,
            gha_workflow::commands::gha_fetch_action_yml,
            ai_provider::detect_ai_providers,
            ai_provider::run_ai_prompt,
            ai_provider::read_env_api_keys,
            secure_store::set_secret,
            secure_store::get_secret,
            secure_store::delete_secret,
            ai_provider::test_api_key,
            ai_provider::list_models,
            ai_provider::validate_model,
            #[cfg(debug_assertions)]
            app_setup::debug_log,
            temp_html::write_temp_html,
            file_write::atomic_write_file,
            webview_edit::trigger_webview_edit,
            browser::commands::browser_create,
            browser::commands::browser_navigate,
            browser::commands::browser_back,
            browser::commands::browser_forward,
            browser::commands::browser_stop,
            browser::commands::browser_dialog_respond,
            browser::commands::browser_set_bounds,
            browser::commands::browser_destroy,
            browser::commands::browser_assert_no_bridge,
            browser::commands_auth::browser_set_grants,
            browser::commands_auth::browser_add_one_shot,
            browser::commands_auth::browser_eval,
            browser::commands::browser_freeze,
            browser::commands::browser_thaw,
            #[cfg(target_os = "macos")]
            dock_recent::register_dock_recent,
            #[cfg(target_os = "macos")]
            pdf_export::commands::export_pdf,
            #[cfg(target_os = "macos")]
            pdf_export::commands::print_document,
            pandoc::commands::detect_pandoc,
            pandoc::commands::export_via_pandoc,
            content_search::search_workspace_content,
            content_server::commands::content_server_start,
            content_server::commands::content_server_stop,
            content_server::commands::content_server_status,
            content_server::commands::content_server_browser_url,
            content_server::commands::content_server_graph,
            content_server::slidev_commands::content_server_slidev_preview,
            content_server::slidev_commands::content_server_slidev_export,
            pty::pty_spawn,
            pty::pty_start,
            pty::pty_write,
            pty::pty_resize,
            pty::pty_kill,
            pty::pty_close,
            pty::pty_pause,
            pty::pty_resume,
            shell_integration::prepare_shell_integration,
        ]
    };
}
